/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const VestingCliff = IDL.Record({
  'cliffPeriod' : IDL.Nat,
  'cliffPercentage' : IDL.Float64,
});
export const VestingStep = IDL.Record({
  'stepPeriod' : IDL.Nat,
  'stepPercentage' : IDL.Float64,
  'stepFrequency' : IDL.Nat,
});
export const Schedule = IDL.Record({
  'id' : IDL.Text,
  'cliff' : VestingCliff,
  'step' : VestingStep,
  'numChunks' : IDL.Nat,
  'lockPeriod' : IDL.Nat,
  'isTokenLock' : IDL.Bool,
  'chunkSize' : IDL.Nat,
});
export const Recipient = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'allocationPercentage' : IDL.Float64,
  'schedule' : Schedule,
});
export const SavedSession = IDL.Record({
  'id' : IDL.Text,
  'decimals' : IDL.Nat,
  'inflationRate' : IDL.Float64,
  'sessionName' : IDL.Text,
  'totalSupply' : IDL.Nat,
  'recipients' : IDL.Vec(Recipient),
  'inflationStartYear' : IDL.Nat,
  'timestamp' : IDL.Int,
  'enableInflation' : IDL.Bool,
});
export const VestingSchedule = IDL.Record({
  'admin' : IDL.Principal,
  'tokenPrice' : IDL.Float64,
  'cliffPeriod' : IDL.Nat,
  'name' : IDL.Text,
  'totalTokens' : IDL.Nat,
  'vestingType' : IDL.Variant({
    'graded' : IDL.Null,
    'cliffLinear' : IDL.Null,
  }),
  'vestingDuration' : IDL.Nat,
  'startDate' : IDL.Int,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteVestingSchedule' : IDL.Func([IDL.Text], [], []),
  'getAllSessions' : IDL.Func([], [IDL.Vec(SavedSession)], ['query']),
  'getAllVestingSchedules' : IDL.Func(
      [],
      [IDL.Vec(VestingSchedule)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getSession' : IDL.Func([IDL.Text], [SavedSession], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVestingSchedule' : IDL.Func([IDL.Text], [VestingSchedule], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'listApprovalsForCurrentUser' : IDL.Func(
      [],
      [IDL.Vec(UserApprovalInfo)],
      ['query'],
    ),
  'requestApproval' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveSession' : IDL.Func([SavedSession], [], []),
  'saveVestingSchedule' : IDL.Func([VestingSchedule], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const VestingCliff = IDL.Record({
    'cliffPeriod' : IDL.Nat,
    'cliffPercentage' : IDL.Float64,
  });
  const VestingStep = IDL.Record({
    'stepPeriod' : IDL.Nat,
    'stepPercentage' : IDL.Float64,
    'stepFrequency' : IDL.Nat,
  });
  const Schedule = IDL.Record({
    'id' : IDL.Text,
    'cliff' : VestingCliff,
    'step' : VestingStep,
    'numChunks' : IDL.Nat,
    'lockPeriod' : IDL.Nat,
    'isTokenLock' : IDL.Bool,
    'chunkSize' : IDL.Nat,
  });
  const Recipient = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'allocationPercentage' : IDL.Float64,
    'schedule' : Schedule,
  });
  const SavedSession = IDL.Record({
    'id' : IDL.Text,
    'decimals' : IDL.Nat,
    'inflationRate' : IDL.Float64,
    'sessionName' : IDL.Text,
    'totalSupply' : IDL.Nat,
    'recipients' : IDL.Vec(Recipient),
    'inflationStartYear' : IDL.Nat,
    'timestamp' : IDL.Int,
    'enableInflation' : IDL.Bool,
  });
  const VestingSchedule = IDL.Record({
    'admin' : IDL.Principal,
    'tokenPrice' : IDL.Float64,
    'cliffPeriod' : IDL.Nat,
    'name' : IDL.Text,
    'totalTokens' : IDL.Nat,
    'vestingType' : IDL.Variant({
      'graded' : IDL.Null,
      'cliffLinear' : IDL.Null,
    }),
    'vestingDuration' : IDL.Nat,
    'startDate' : IDL.Int,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteVestingSchedule' : IDL.Func([IDL.Text], [], []),
    'getAllSessions' : IDL.Func([], [IDL.Vec(SavedSession)], ['query']),
    'getAllVestingSchedules' : IDL.Func(
        [],
        [IDL.Vec(VestingSchedule)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getSession' : IDL.Func([IDL.Text], [SavedSession], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVestingSchedule' : IDL.Func([IDL.Text], [VestingSchedule], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'listApprovalsForCurrentUser' : IDL.Func(
        [],
        [IDL.Vec(UserApprovalInfo)],
        ['query'],
      ),
    'requestApproval' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveSession' : IDL.Func([SavedSession], [], []),
    'saveVestingSchedule' : IDL.Func([VestingSchedule], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };