/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Recipient {
  'id' : string,
  'name' : string,
  'allocationPercentage' : number,
  'schedule' : Schedule,
}
export interface SavedSession {
  'id' : string,
  'decimals' : bigint,
  'inflationRate' : number,
  'sessionName' : string,
  'totalSupply' : bigint,
  'recipients' : Array<Recipient>,
  'inflationStartYear' : bigint,
  'timestamp' : bigint,
  'enableInflation' : boolean,
}
export interface Schedule {
  'id' : string,
  'cliff' : VestingCliff,
  'step' : VestingStep,
  'numChunks' : bigint,
  'lockPeriod' : bigint,
  'isTokenLock' : boolean,
  'chunkSize' : bigint,
}
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VestingCliff {
  'cliffPeriod' : bigint,
  'cliffPercentage' : number,
}
export interface VestingSchedule {
  'admin' : Principal,
  'tokenPrice' : number,
  'cliffPeriod' : bigint,
  'name' : string,
  'totalTokens' : bigint,
  'vestingType' : { 'graded' : null } |
    { 'cliffLinear' : null },
  'vestingDuration' : bigint,
  'startDate' : bigint,
}
export interface VestingStep {
  'stepPeriod' : bigint,
  'stepPercentage' : number,
  'stepFrequency' : bigint,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteVestingSchedule' : ActorMethod<[string], undefined>,
  'getAllSessions' : ActorMethod<[], Array<SavedSession>>,
  'getAllVestingSchedules' : ActorMethod<[], Array<VestingSchedule>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getSession' : ActorMethod<[string], SavedSession>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVestingSchedule' : ActorMethod<[string], VestingSchedule>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'listApprovalsForCurrentUser' : ActorMethod<[], Array<UserApprovalInfo>>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveSession' : ActorMethod<[SavedSession], undefined>,
  'saveVestingSchedule' : ActorMethod<[VestingSchedule], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];